webots_ros2_core/CHANGELOG.rst
webots_ros2_core/package.xml
webots_ros2_core/webots_ros2_core/laser_publisher.py
webots_ros2_core/webots_ros2_core/tf_publisher.py

This PR adds a laser module that allows the user to publish the lidar values as laser-scan.
This module is made generic so it will work with any lidar node, but the arguments of the constructor allow the user to customize it (e.g. for specific update frequencies or topic names).

Feature Laser Module

---

.travis.yml

As ROS crystal is not supported anymore (end of life December 2019) and often causing the python API is not compatible with Dashing and Eloquent I think we can skip this distribution from now.

Remove ROS Crystal

---

webots_ros2_core/webots_ros2_core/webots_launcher.py

This was failing if more than on argument was provided (for example in the AWS Robomaker case).

Fix Webots Arguments Issues

---

webots_ros2_examples/CHANGELOG.rst
webots_ros2_examples/package.xml
webots_ros2_examples/webots_ros2_examples/example_controller.py

Extend `webots_ros2_examples` with a new method to set motor velocity. Instead of using a client/service, now it can be used with a subscriber/publisher.
- `webots_ros2_examples`

Extend webots_ros2_examples

---

webots_ros2_epuck/README.md
webots_ros2_epuck/webots_ros2_epuck/drive_calibrator.py

This PR improves support for differential drive calibration (similar to [this](http://www-personal.umich.edu/~johannb/Papers/paper58.pdf)) to better estimate distance between the wheels and wheel radius.
**Tasks**
The initial idea was to fully automate the calibration process (branch `feature-auto-diffdrive-calib`) by using the ToF sensor for determining the number of rotations (landmark created based on two sequential readings) and passed distance:
https://github.com/cyberbotics/webots_ros2/blob/feature-auto-diffdrive-calib/webots_ros2_epuck/webots_ros2_epuck/drive_calibrator.py
Although the process worked in the simulation, detecting landmarks is not possible with the physical robot (FoV is too wide, fixed …

Improve Support for Differential Drive Calibration

---

webots_ros2_core/test/test_flake8.py
webots_ros2_core/webots_ros2_core/joint_state_publisher.py
webots_ros2_core/webots_ros2_core/laser_publisher.py
webots_ros2_core/webots_ros2_core/tf_publisher.py
webots_ros2_core/webots_ros2_core/trajectory_follower.py
webots_ros2_core/webots_ros2_core/webots_node.py
webots_ros2_demos/webots_ros2_demos/follow_joint_trajectory_client.py
webots_ros2_epuck/webots_ros2_epuck/driver.py

Nanoseconds are not calculated properly.
Fixes #71
- webots_ros2_demos
**Tasks**
**Additional Context**
- Users can use either `Time(seconds=self.robot.getTime()).to_msg()` or `self.get_clock().now().to_msg()`

Replace .now() method

---

webots_ros2_abb/launch/abb_irb4600.launch.py
webots_ros2_demos/launch/armed_robots.launch.py
webots_ros2_epuck/launch/robot_launch.py
webots_ros2_epuck/launch/robot_tools_launch.py
webots_ros2_examples/launch/example.launch.py
webots_ros2_tiago/launch/tiago.launch.py
webots_ros2_universal_robot/launch/universal_robot.launch.py
webots_ros2_universal_robot/launch/universal_robot_multiple.launch.py
webots_ros2_universal_robot/launch/universal_robot_rviz.launch.py
webots_ros2_ur_e_description/launch/ur5e_state_publisher.launch.py

Fixes deprecation warning of `node_executable`:
```
/home/lukic/ros_foxy/install/webots_ros2_abb/share/webots_ros2_abb/abb_irb4600.launch.py:35: UserWarning: The parameter 'node_executable' is deprecated, use 'executable' instead
arguments=arguments, output='screen')
/home/lukic/ros_foxy/install/webots_ros2_abb/share/webots_ros2_abb/abb_irb4600.launch.py:41: UserWarning: The parameter 'node_executable' is deprecated, use 'executable' instead
output='screen')
```
- webots_ros2_abb
- webots_ros2_demos
- webots_ros2_examples
- webots_ros2_tiago
- webots_ros2_universal_robot
- webots_ros2_ur_e_description

Fix Deprecated `node_executable`

---

webots_ros2_core/webots_ros2_core/webots_differential_drive_node.py
webots_ros2_epuck/webots_ros2_epuck/drive_calibrator.py

Using sys.exit is recommended instead of using directly exit (because for example this handles exceptions).

Replace exit by sys.exit.

---

.github/workflows/bloom-release.yml

Ok, I think I understood how it works, there is no way to set the branch, even by forking the action for switching branch with git, because the repo is not cloned locally.
Instead, bloom-release will look in rosdep which branch is configured for this ros version and use it automatically.

Fix Bloom Release (last attempt)

---

.github/workflows/bloom-release.yml

The first release on a new ros version has to be created manually (which is not done for eloquent yet, but for foxy).

Remove Eloquent from Workflow

---

webots_ros2_core/webots_ros2_core/joint_state_publisher.py

Use the name of the motor instead the name of the positionSensor as the published joint name. This is more consistent with ROS convention

Use motor name for Joint_states_publisher

---

webots_ros2_desktop/package.xml
webots_ros2_desktop/setup.py

Currently the download of Webots with urlib is failing on the ros buildfarm, I found one package (`fzi_icl_can`) that is using wget successfully on the buildfarm.
It is an old package and a different version of ROS (and therefore the ROS1 buildfarm and not ROS2), but it is worth
trying.

Use wget to get Webots instead of urllib.

---

webots_ros2_core/webots_ros2_core/utils.py

This PR fixes `Can't mix strings and bytes in path components` by decoding path from `which` command.
It also introduces minor changes to avoid potential recursions (`get_webots_version` <-> `get_webots_home`).
Fixes #144, fixes #145
**Tasks**

Decode path from `which` command

---

webots_ros2_ur_e_description/urdf/ur5e_robot.urdf

While preparing the package for the next release:
https://github.com/cyberbotics/webots_ros2/wiki/Internal-Tests
I spotted there are some errors in the terminal due to extra links (I believe that some of them are added to work with deprecated [TF publisher](https://github.com/cyberbotics/webots_ros2/blob/master/webots_ros2_core/webots_ros2_core/tf_publisher.py)) in the URDF file when running:
```
ros2 launch webots_ros2_universal_robot universal_robot_rviz.launch.py
```

Remove unnecessary joints from the UR5e proto

---

webots_ros2_importer/package.xml

Fixes #183
`lark` is dependency of `launch` that typically gets installed with `ros-base`, so we didn't notice it earlier:
https://github.com/ros2/launch/blob/55ca523ff0053e1c7932debaa7366e33180c23a6/launch/package.xml#L17

Add `lark` dependency

---

.github/workflows/test.yml
webots_ros2/package.xml
webots_ros2/setup.py
webots_ros2_abb/package.xml
webots_ros2_abb/setup.py
webots_ros2_core/package.xml
webots_ros2_core/setup.py
webots_ros2_demos/package.xml
webots_ros2_demos/setup.py
webots_ros2_epuck/package.xml
webots_ros2_epuck/setup.py
webots_ros2_examples/package.xml
webots_ros2_examples/setup.py
webots_ros2_importer/package.xml
webots_ros2_importer/setup.py
webots_ros2_msgs/package.xml
webots_ros2_tesla/package.xml
webots_ros2_tesla/setup.py
webots_ros2_tiago/package.xml
webots_ros2_tiago/setup.py
webots_ros2_turtlebot/package.xml
webots_ros2_turtlebot/setup.py
webots_ros2_tutorials/package.xml
webots_ros2_tutorials/setup.py
webots_ros2_universal_robot/package.xml
webots_ros2_universal_robot/setup.py
webots_ros2_ur_e_description/package.xml
webots_ros2_ur_e_description/setup.py

I am also deleting the Rolling tests as there are missing packages: `vision_msgs` and `ackermann_msgs`. I posted an issue about the missing packages:
- https://github.com/ros-perception/vision_msgs/issues/55
- https://github.com/ros-drivers/ackermann_msgs/issues/14#issuecomment-816511743
As soon as the packages are available I will enable the CI tests for Rolling. Now, the plan is to create a `rolling` branch and delete all our packages that depend on the missing packages.

Bump the version number

---

webots_ros2_tesla/webots_ros2_tesla/lane_follower.py

Fixing a bug where the lane_follower node crashes when the road central line is not detected (E.G. at a crossroad). Also adjusted lower and upper bounds for color detection, as well as control coefficient for smoother running.
This pull-request fixes issue #214 
- webots_ros2_tesla
The Ackermannrive message is instantiated before checking for contours in the image, with default values for speed = 50 and steering_angle = 0.0. If contours are detected, then steering_angle is recalculated accordingly. To avoid float division by 0 (which was causing the issue), a further check is inserted for the m00 moment of the largest contour center to be nonzero.
Previous boundaries for color …

Fix crash on no line detection (#214)

---

webots_ros2_core/webots_ros2_core/webots_node.py

Arg `name` is only used in `super().__init__(name)` which is init function of rclpy.node.Node
In rclpy/node.py :
``` python
class Node:
PARAM_REL_TOL = 1e-6
"""
A Node in the ROS graph.
A Node is the primary entrypoint in a ROS system for communication.
It can be used to create ROS entities such as publishers, subscribers, services, etc.
"""
def __init__(
self,
node_name: str,
*,
context: Context = None,
cli_args: List[str] = None,
namespace: str = None,
use_global_arguments: bool = True,
enable_rosout: bool = True,
start_parameter_services: bool = True,
parameter_overrides: List[Parameter] = None,
allow_undeclared_parameters: bool = False,
automatically_declare_parameters_from_overrides: bool = False
) -> None:
```
So, revise the arg type in docstring from `WebotNode` to …

Revise argument's type of WebotsNode init func

---

webots_ros2_driver/CMakeLists.txt

Since the colcon moves the targets to the `/install` directory the lib controller wasn't linking properly for runtime

Link libcontroller correctly at runtime

---

webots_ros2_turtlebot/launch/robot_launch.py

The TurtleBot launch file now automatically starts controllers (`diffdrive_controller` and `joint_state_broadcaster`)
The prefix trick is needed until either of these is released (it takes more than 10s to load the simulation, so the spawner fails):
- https://github.com/ros-controls/ros2_control/pull/444
- https://github.com/ros2/launch/pull/514

Add controller manager spawner to the TurtleBot launch file

---

webots_ros2_core/webots_ros2_core/webots_launcher.py

Hey, this is my first PR. So please point everything wrong out.
As seen in https://github.com/cyberbotics/webots/pull/2286 an option ` --no-rendering` was added to Webots 2021b.
This should be a standard option for the webots launcher if gui:=false.

Added new  ` --no-rendering` option to webots launcher

---

webots_ros2_control/src/Ros2Control.cpp
webots_ros2_tiago/worlds/ros_tiago.wbt
webots_ros2_turtlebot/worlds/turtlebot3_burger_example.wbt

The change in `Ros2Control.cpp` fixes the following warning:
```
/home/lukic/foxy_ws/src/webots_ros2/webots_ros2_control/src/Ros2Control.cpp:40:110: warning: unused parameter ‘parameters’ [-Wunused-parameter]
```
Some parameters in the `DirectionPanel` are deleted, so we have to delete them in the world file as well.

Fix warnings

---

webots_ros2_driver/CMakeLists.txt
webots_ros2_driver/src/plugins/static/Ros2Camera.cpp
webots_ros2_turtlebot/launch/robot_launch.py

This PR attempts to fix the Windows build. There was a series of issues:
- The C++ libController library has to be compiled, it cannot be linked.
- The libController couldn't be linked as it was in the wrong place (Windows only).
- The `id` parameter in the `ObjectHypothesisWithPose` message is deprecated.
- The controller spawners were broken in Windows.
**Notes**
```
colcon build --event-handlers console_cohesion+ --packages-select webots_ros2_driver
```

Fix Windows build

---

webots_ros2_driver/src/plugins/dynamic/Ros2IMU.cpp
webots_ros2_driver/src/plugins/static/Ros2Camera.cpp
webots_ros2_driver/src/plugins/static/Ros2DistanceSensor.cpp
webots_ros2_driver/src/plugins/static/Ros2GPS.cpp
webots_ros2_driver/src/plugins/static/Ros2Lidar.cpp
webots_ros2_driver/src/plugins/static/Ros2LightSensor.cpp
webots_ros2_driver/src/plugins/static/Ros2RangeFinder.cpp
webots_ros2_turtlebot/launch/robot_launch.py

If `use_sim_time = True` the lidar scan message timestamp should use sim time.
This pull-request fixes issue #260
Some more devices uses the same old behaviour (e.g. Ros2GPS). I don't know if i should fix this too.
I added the launch file changes too. Should i remove them from the PR?

Use ros2 node clock for message timestamping

---

.github/workflows/test.yml
webots_ros2/setup.cfg
webots_ros2_abb/setup.cfg
webots_ros2_core/setup.cfg
webots_ros2_demos/setup.cfg
webots_ros2_driver/CMakeLists.txt
webots_ros2_driver/src/PythonPlugin.cpp
webots_ros2_epuck/setup.cfg
webots_ros2_examples/setup.cfg
webots_ros2_importer/setup.cfg
webots_ros2_mavic/setup.cfg
webots_ros2_tesla/setup.cfg
webots_ros2_tiago/setup.cfg
webots_ros2_turtlebot/setup.cfg
webots_ros2_turtlebot/webots_ros2_turtlebot/plugin_example.py
webots_ros2_tutorials/setup.cfg
webots_ros2_universal_robot/setup.cfg
webots_ros2_ur_e_description/setup.cfg

The PR fixes warnings from the build farm:
```
/usr/local/lib/python3.8/dist-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
/usr/local/lib/python3.8/dist-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
```
- https://build.ros2.org/job/Rdev__webots_ros2__ubuntu_focal_amd64/42/console
Also, the `ament_python_install_package` seems to doesn't support creating subpackages. It is something it was working perfectly in Foxy, but Rolling breaks the behavior (the issue is reported). As a solution, we store the Python libController to …

Fix Rolling warnings and `ament_python_install_package`

---

webots_ros2_driver/src/WebotsNode.cpp

This PR reverts changes made in #283.
The `get_node_names` never returns the `robot_state_publisher` node on Linux. @dzywater we have to find another way to check whether the `robot_state_publisher` node exists.

Revert `robot_state_publisher` check

---

webots_ros2_core/webots_ros2_core/devices/camera_device.py

This PR is to fix a call of wb_camera_recognition_disable() on a Camera without Recognition node in webots_ros2_core/camera_device.py.
This pull-request fixes issue #242 
**Solution**
Fixed by simply checking if the Camera has a Recognition node before call wb_camera_recognition_disable().

fix call we_camera_recognition_disable() on NULL recognition node

---

webots_ros2_driver/src/plugins/static/Ros2Lidar.cpp

Even though RViz works well, slam_toolbox complains about a missing reading

Fix Lidar range

---

webots_ros2_tests/test/test_system_universal_robot.py
webots_ros2_universal_robot/launch/multirobot_launch.py
webots_ros2_universal_robot/webots_ros2_universal_robot/abb_controller.py
webots_ros2_universal_robot/webots_ros2_universal_robot/follow_joint_trajectory_client.py
webots_ros2_universal_robot/webots_ros2_universal_robot/ur5e_controller.py

This PR is to solve the random failure due to time out for the system test of `universal robot`.
This pull-request fixes issue #310.

Fix universal robot system tests random faillure

---

.github/workflows/test.yml
webots_ros2_control/CMakeLists.txt
webots_ros2_control/include/webots_ros2_control/Ros2Control.hpp
webots_ros2_control/include/webots_ros2_control/Ros2ControlSystem.hpp
webots_ros2_control/include/webots_ros2_control/Ros2ControlSystemInterface.hpp
webots_ros2_control/src/Ros2Control.cpp
webots_ros2_control/src/Ros2ControlSystem.cpp
webots_ros2_tesla/webots_ros2_tesla/lane_follower.py
webots_ros2_universal_robot/resource/ros2_control_abb_config.yaml
webots_ros2_universal_robot/resource/ros2_control_config.yaml

This PR is to solve the romve of `base_interface` from `hardware_interface` from `ros2control` as it makes the rolling testing test fail on CI.
Also it impacts `ROS Galactic`.
This take work from @Timple from this PR #313 and insure compatibility with `foxy`.

Correction for Rolling CI testing failling due to change in ros2control (base_interface)

---

webots_ros2_driver/include/webots_ros2_driver/plugins/static/Ros2LED.hpp
webots_ros2_driver/src/plugins/static/Ros2LED.cpp
webots_ros2_tests/test/test_system_driver.py

The LED topic was broken: it was expecting a message of type `ColorRGBA` which is not compatible with all the possibilities of LED devices in Webots (indexed, gradual, RGB). This PR reverts to using a `Int32` message type to be closer to the Webots API and allow all the use cases.
I updated the [tutorial about it](https://github.com/cyberbotics/webots_ros2/wiki/Tutorial-E-puck-for-ROS2-Beginners).

Fixed broken LED

---

webots_ros2_control/package.xml

This should solved the issue on the buildfarm as `ROS_DISTRO` is not defined.
Including the `ros_environnement` package should solve this according to this [PR](https://github.com/ros/rosdistro/issues/29465).

Fix buildfarm withour ROS_DISTRO defined

---

webots_ros2_control/CMakeLists.txt
webots_ros2_control/package.xml
webots_ros2_driver/CMakeLists.txt
webots_ros2_driver/package.xml

`webots_ros2_driver` doesn't depend on `rclcpp_lifecycle`, but `webots_ros2_control` only

Move `rclcpp_lifecycle` dependency to `webots_ros2_control`

---

webots_ros2_tiago/launch/robot_launch.py

Make sure Tiago simulation doesn't crash on `get_package_share_directory('nav2_bringup')`. Note that Navigation2 is not released to Rolling, so we cannot explicitly make it a dependency.

Make Navigation2 optional

---

webots_ros2_control/CMakeLists.txt
webots_ros2_driver/CMakeLists.txt

Export libController include files, so plugin developers don't have to include them explicitly

Simplify C++ plugins

---

webots_ros2_control/CMakeLists.txt
webots_ros2_driver/CMakeLists.txt

fix link error when build libwebots_ros2_control_system.dylib on macOS
ros2 version : foxy
operating system : macOS catalina
✅ Closes: #344
fix Link error when build libwebots_ros2_control_system.dylib on macOS
This pull-request fixes issue #344 
- webots_ros2_controller
Maybe there have some issues to build webs_ros2 package on macOS Catalina if you install ros2 from binary package,
here is solutions:
```
rosinstall_generator ros2_control control_msgs ros2_controllers controller_interface controller_manager controller_manager_msgs hardware_interface joint_limits_interface ros2_control_test_assets ros2controlcli transmission_interface --rosdistro foxy > deps.repos
mkdir src
vcs …
```

fix: 🐛 link error when build libwebots_ros2_control on macOS

---

webots_ros2_core/webots_ros2_core/utils.py
webots_ros2_driver/src/plugins/static/Ros2Lidar.cpp
webots_ros2_driver/webots_ros2_driver/utils.py
webots_ros2_tests/test/test_system_driver.py
webots_ros2_tests/worlds/driver_test.wbt
webots_ros2_turtlebot/resource/ros2control.yml
webots_ros2_universal_robot/package.xml

Fixes #366
**Tasks**
- Not related problems:
**Note**
- The tests are passing without the MoveIt dependency, so it seems there is a temporary problem on the ROS side.
- It might be possible that we inverted the order of the LiDAR scan in Webots.
- We should do another release with this fix as soon as possible (before ROS syncs).

Fix LiDAR transform

---

webots_ros2_driver/include/webots_ros2_driver/WebotsNode.hpp
webots_ros2_driver/src/WebotsNode.cpp
webots_ros2_epuck/launch/robot_launch.py
webots_ros2_tiago/launch/robot_launch.py
webots_ros2_turtlebot/launch/robot_launch.py
webots_ros2_universal_robot/launch/robot_launch.py

Currently `webots_ros2_driver` automatically publish a `robot_description` obtained with `mRobot->getUrdf()` (so the URDF obtained is corresponding either to the PROTO used or to the robot node in the world file) for the `robot_state_publisher` node.
The issue is that `webots_ros2_driver` override the parameter `robot_description`, so a user cannot set it himself. It would be preferable to have an option to specify if `webots_ros2_driver` should publish this `robot_description` in case someone is using a PROTO and in the case the user has an URDF file, he can specify `robot_description` for the `robot_state_publisher` node in the launch file.
This pull-request fixes issue #375

Create an option for "webots_ros2_driver" to publish "robot_description" for "robot_state_publisher" node

---

scripts/ci_after_init.bash
scripts/ci_before_init_embed.bash

In order to be up to date with the `master` and `develop` branches from the `webots` repos, it is better to use nightly build of Webots instead of the official releases in order to get the latest features and bug fixes

Change CI tests to use the latest Webots nightly build

---

webots_ros2_core/CHANGELOG.rst
webots_ros2_core/README.md
webots_ros2_core/package.xml
webots_ros2_core/setup.py
webots_ros2_core/webots_ros2_core/__init__.py
webots_ros2_mavic/package.xml
webots_ros2_tests/test/test_system_driver.py

`webots_ros2_core` has been deprecated in favor of `webots_ros2_driver` for almost 6 months but there was no indication or warning for the user when using the interface.
This PR add a warning during the build from source and when using the package.
This pull-request partially fixes issue #359.

Fix deprecation warnings webots ros2 core

---

webots_ros2_driver/src/plugins/static/Ros2Lidar.cpp

Addresses: https://github.com/cyberbotics/webots_ros2/issues/424
Currently on the tiago example, slam_toolbox complains about the number of range readings not matching.
The change was introduced here https://github.com/cyberbotics/webots_ros2/pull/367, however I'm not certain why. As far as I can tell, for slam_toolbox the range should be inclusive, so `[-0.5*FOV, 0.5*FOV]`, which is also how it was implemented in [webots_ros2_core ](https://github.com/cyberbotics/webots_ros2/blob/2ad205c9118c91ca442ac052073bb81333561c8a/webots_ros2_core/webots_ros2_core/devices/lidar_device.py#L131-L133). @lukicdarkoo do you recall perhaps why the change was done?

Fix laser publisher

---

webots_ros2_control/CMakeLists.txt

The `webots_ros2_control::Ros2ControlSystem` hardware_interface is generic and it should work for most users. However, sometimes users need to implement a custom `hardware_interface` (e.g. to achieve a certain control behavior). This PR exports the necessary headers for custom interfaces (if I get time I may write a tutorial about it).

Allow custom ros2_control hardware_interface

---

webots_ros2_driver/include/webots_ros2_driver/PluginInterface.hpp

Compiling on ROS2 Rolling, the following error occurs. Simply adding ``#include <string>`` fixes the issue.
```
In file included from /home/ijnek/workspaces_ros2/webots_ros2_ws/src/webots_ros2/webots_ros2_driver/include/webots_ros2_driver/PythonPlugin.hpp:21,
from /home/ijnek/workspaces_ros2/webots_ros2_ws/src/webots_ros2/webots_ros2_driver/src/PythonPlugin.cpp:1:
/home/ijnek/workspaces_ros2/webots_ros2_ws/src/webots_ros2/webots_ros2_driver/include/webots_ros2_driver/PluginInterface.hpp:35:69: error: ‘string’ is not a member of ‘std’
35 |         virtual void init(WebotsNode *node, std::unordered_map<std::string, std::string> &parameters) = 0;
```
This pull-request fixes issue #

include string

---

webots_ros2_core/webots_ros2_core/devices/camera_device.py
webots_ros2_driver/CMakeLists.txt
webots_ros2_driver/package.xml
webots_ros2_driver/src/plugins/static/Ros2Camera.cpp

Match vision_msgs bbox msg to new signature, released in [4.0.0 on **Rolling only**](https://github.com/ros/rosdistro/pull/32485). 
**Error**
Error log when compiling:
```
error: ‘using _center_type = struct vision_msgs::msg::Pose2D_<std::allocator<void> >’ {aka ‘struct vision_msgs::msg::Pose2D_<std::allocator<void> >’} has no member named ‘x’
```
No Related Issues
Do not back port this to galactic or foxy

use new bbox msg signature

---

webots_ros2_core/webots_ros2_core/devices/camera_device.py

PEP257 is failing on rolling with:
```
_________________________________ test_pep257 __________________________________
test/test_pep257.py:25: in test_pep257
assert rc == 0, 'Found code style errors / warnings'
E   AssertionError: Found code style errors / warnings
E   assert 1 == 0
----------------------------- Captured stdout call -----------------------------
...
checking ./webots_ros2_core/devices/camera_device.py
./webots_ros2_core/devices/camera_device.py:30 in public class `CameraDevice`: D407: Missing dashed underline after section ('Args')
```
No related issue
This error is showing up in [industrial_ci (main, …

Fix pep257 D407 Missing dashed underline after section

---

webots_ros2_driver/CMakeLists.txt

Use Python 3.10 for Rolling on Ubuntu Jammy to fix current CI failure.
**This requires the auto-generated python310 directory in https://github.com/cyberbotics/webots-libcontroller/tree/R2022b/lib/linux-gnu before being merged**, (related to https://github.com/cyberbotics/webots/pull/4474)
Current error log when compiling on Ubuntu Jammy:
```
--- stderr: webots_ros2_driver
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
(Required is exact version "3.8")
Call Stack (most recent call first):
/usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
/usr/share/cmake-3.22/Modules/FindPythonLibs.cmake:310 …
```

bump python version to 3.10 for rolling

---

webots_ros2_epuck/launch/robot_launch.py
webots_ros2_tiago/launch/robot_launch.py
webots_ros2_turtlebot/launch/robot_launch.py
webots_ros2_universal_robot/launch/multirobot_launch.py
webots_ros2_universal_robot/launch/robot_launch.py

``spawner.py`` was deprecated in ROS2 Galactic and removed in ROS2 Rolling in https://github.com/ros-controls/ros2_control/commit/ec0ec193cc09e449d5525e34e38040432fce5511.
It should be replaced by ``spawner``.
Galactic supports both ``spawner.py`` and ``spawner``, so we only have to deal with Foxy. (https://github.com/ros-controls/ros2_control/blob/67bf0a59a6908d9bfd385a05fdcfe3944c7bbb07/controller_manager/CMakeLists.txt#L58)
No related issue
- webots_ros2_tiago
- webots_ros2_turtle
- webots_ros2_universal_robot
This error is showing up in [industrial_ci (main, rolling)](https://github.com/cyberbotics/webots_ros2/runs/6185995564?check_suite_focus=true) of …

Change call to spawner.py executable to spawner

---

scripts/ci_after_init.bash

Due to the merge of webots develop into master, nightlies for R2022a are no longer created/available so we need to target R2022a itself.

Fix master nightly

---

webots_ros2_driver/webots_ros2_driver/urdf_spawner.py
webots_ros2_driver/webots_ros2_driver/utils.py
webots_ros2_driver/webots_ros2_driver/webots_launcher.py
webots_ros2_epuck/launch/robot_launch.py
webots_ros2_mavic/launch/robot_launch.py
webots_ros2_tesla/launch/robot_launch.py
webots_ros2_tests/test/test_system_driver.py
webots_ros2_tiago/launch/robot_launch.py
webots_ros2_turtlebot/launch/robot_launch.py
webots_ros2_universal_robot/launch/multirobot_launch.py
webots_ros2_universal_robot/launch/robot_launch/robot_nodes_launch.py

Currently, the documentation and tutorials detail how to use `webots_ros2` on Windows and the package officially supports installation on this platform. However, using ROS2 outside of a Linux environment is not trivial and many other distributed packages are not maintained for macOS or Windows.
This PR deprecates the compatibility with Windows, but adds the possibility to run the package in WSL (Windows Subsystem for Linux). This way Webots still runs on Windows, while the whole ROS2 part can be run in a Linux environment, which greatly increases the simplicity of package maintenance, usage and the possibility to use other distributed packages. In short, the experience of Windows users is greatly improved and simplified.
In addition, this PR changes the way Webots is searched in the …

Replace Windows compatibility with WSL

---

webots_ros2_driver/webots_ros2_driver/webots_launcher.py

In #481, the Windows compatibility was first removed, and then restored again. This PR restores a forgotten part, causing `webots_ros2` to exit directly on Windows. Windows should be still compatible for a few time to allow users to switch to the WSL solution.

Restore windows compatibility and update deprecation message

---

webots_ros2_driver/webots_ros2_driver/webots_launcher.py

As reported by a user, relative PROTO were not being found. Due to the introduction of ROS2Supervisor, the world file needs to be edited prior to launching it in order to append the VRML of the ROS2Supervisor node. The edited copy is launched from /tmp, and relative urls of assets are adjusted accordingly. The replacement logic however is more strict than it needs to (requiring `url something`) and didn't apply to PROTO.

Fix relative PROTO not being found

---

.github/workflows/libcontroller_updater.yml

Proof of concept for automatic creation of PRs when a sync of libcontroller is necessary.
It's also possible to have a workflow (in libcontroller repo) that triggers when something gets merged such that it dispatches an event to this repo, triggering a workflow here which opens the PR. For our purpose however that would be overkill as the libcontroller repo gets updated at most once per day (when the nightlies are created), if even that. It's sufficient to check daily.

Automatic libcontroller sync

---

.github/workflows/libcontroller_updater.yml
.github/workflows/test.yml
.github/workflows/test_develop.yml

The libcontroller sync appears to have worked as intended.
This PR:
- Change the time when nighty tests are run (currently the time set is fairly overlapping with the time when the deb itself is generated, so might lead to odd runs if there are delays/slow machines)
- Change the time the sync check is done (early morning, so we have the full day to do something about it if something breaks)
- Make so that workflows currently being run are canceled if a new push occurs (currently it keeps running and a new run is launched for every commit)

Adjust nightly timings and concurrency

---

README.md

The link to the `Build and Install` wiki page is no longer working.
Not sure if the new documentation page is still a work in progress.

Update link to wiki page in README.md

---

webots_ros2_epuck/launch/robot_launch.py
webots_ros2_mavic/launch/robot_launch.py
webots_ros2_tesla/launch/robot_launch.py
webots_ros2_tiago/launch/robot_launch.py
webots_ros2_turtlebot/launch/robot_launch.py

Currently only the universal robot example can be reset from Webots. Once reset the controllers are able to respawn and connect to each robot again. This PR updates all examples so that their controllers can respawn and reconnect after a reset.

Enhancement: allow world reset on every samples

---

webots_ros2/CHANGELOG.rst
webots_ros2_driver/CHANGELOG.rst
webots_ros2_driver/src/plugins/static/Ros2Camera.cpp

It seems that FoV in Webots is actually horizontal FoV. With these values, I get results quite close to the ground truth.
It would be good to double-check this.

Fix camera focal length

---

webots_ros2/CHANGELOG.rst
webots_ros2_driver/CHANGELOG.rst
webots_ros2_driver/CMakeLists.txt
webots_ros2_driver/include/webots_ros2_driver/plugins/static/Ros2Camera.hpp
webots_ros2_driver/package.xml
webots_ros2_driver/src/plugins/static/Ros2Camera.cpp
webots_ros2_tests/CHANGELOG.rst
webots_ros2_tests/test/test_system_driver.py
webots_ros2_tests/worlds/.driver_test.wbproj
webots_ros2_tests/worlds/driver_test.wbt

Calculation now conforms to the new camera coordinate frame introduced with Webots R2022b.
Signed-off-by: Andreas Kreutz <andreas.kreutz@hotmail.de>
With the release of Webots R2022b, the coordinate frame for cameras has been changed. This means that the calculation of `CameraRecognitionObject` messages needs to be updated. 
This pull-request fixes issue #517 
- webots_ros2_tests

Update calculation of `CameraRecognitionObject`

---

webots_ros2_driver/CMakeLists.txt

Attempts to fix #567.
Symlinks to the libController binaries were not created in the buildfarm because of permissions, leading to a broken released package. 
This PR attempts to create the symlinks with the cmake command instead of `ln -sf`.

cmake symlinks

---

webots_ros2_driver/include/webots_ros2_driver/plugins/static/Ros2Camera.hpp

Replaces deprecated `<tf2_geometry_msgs/tf2_geometry_msgs.h>` with `<tf2_geometry_msgs/tf2_geometry_msgs.hpp>` in Rolling and Humble. This change was introduced in #523 and was causing a deprecation warning when compiling the package on Humble and Rolling.

Resolving Deprecation Warning with Header File Replacement

---

webots_ros2_driver/CMakeLists.txt

Follow-up to #569 attempt to fix #567.
The creation of symlinks seems impossible in the library directory. The new structure with the 'controller' directory being mandatory for the new Python API to work, another solution must be applied. Using CMAKE RPATH, it is possible to specify the location of shared libraries at runtime (i.e. in the install directory), allowing to specify to compiled executables the location of the libController.

Remove symlinks and add shared libs to rpath

---

webots_ros2/CHANGELOG.rst
webots_ros2_driver/CHANGELOG.rst
webots_ros2_driver/webots_ros2_driver/webots_launcher.py

On WSL, worlds referring to local protos could not be loaded because the path is not correctly modified in the world file.

WSL error: local PROTOs cannot be loaded

---

webots_ros2/CHANGELOG.rst
webots_ros2_epuck/CHANGELOG.rst
webots_ros2_epuck/worlds/rats_life_benchmark.wbt

The name of the epuck in the rats life example is not consistent with the one in the basic epuck example. The robot_launch.py script is failing for the rats life example

Fix rats life example launcher

---

webots_ros2_epuck/launch/robot_launch.py
webots_ros2_epuck/worlds/epuck_world.wbt
webots_ros2_epuck/worlds/rats_life_benchmark.wbt

#574 fixed the name from `e-puck` to `epuck` in the rats life example.
To be consistent with the default name of the E-puck, this PR reverts the change and modifies the name from `epuck` to `e-puck` in the launcher and the epuck_world instead.

Revert E-puck name to `e-puck`

---

webots_ros2/CHANGELOG.rst
webots_ros2_driver/CHANGELOG.rst
webots_ros2_driver/webots_ros2_driver/webots_launcher.py

Fixes #583.
The local assets referenced with relative URL in the world files are copied to the shared folder on macOS. Their URL is also updated to reflect the new relative path to the world.

Fix macOS local assets with relative URLs

---

webots_ros2/CHANGELOG.rst
webots_ros2_driver/CHANGELOG.rst
webots_ros2_driver/webots_ros2_driver/webots_launcher.py
webots_ros2_epuck/CHANGELOG.rst
webots_ros2_epuck/launch/robot_launch.py
webots_ros2_mavic/CHANGELOG.rst
webots_ros2_mavic/launch/robot_launch.py
webots_ros2_tesla/CHANGELOG.rst
webots_ros2_tesla/launch/robot_launch.py
webots_ros2_tiago/CHANGELOG.rst
webots_ros2_tiago/launch/robot_launch.py
webots_ros2_turtlebot/CHANGELOG.rst
webots_ros2_turtlebot/launch/robot_launch.py
webots_ros2_universal_robot/CHANGELOG.rst
webots_ros2_universal_robot/launch/multirobot_launch.py
webots_ros2_universal_robot/launch/robot_launch/robot_world_launch.py

Resolves #509.
The Ros2 supervisor is now optional and is created by the WebotsLauncher Node. The supervisor node can still be used in the launch file if necessary. 
If the Ros2 supervisor is created, it still must figure in the launch description of the launch file, so that it gets started with other nodes.

Optional Ros2 Supervisor

---

webots_ros2/CHANGELOG.rst
webots_ros2_driver/CHANGELOG.rst
webots_ros2_driver/webots_ros2_driver/ros2_supervisor.py
webots_ros2_driver/webots_ros2_driver/urdf_spawner.py
webots_ros2_epuck/CHANGELOG.rst
webots_ros2_mavic/CHANGELOG.rst
webots_ros2_tesla/CHANGELOG.rst
webots_ros2_tiago/CHANGELOG.rst
webots_ros2_turtlebot/CHANGELOG.rst
webots_ros2_universal_robot/CHANGELOG.rst
webots_ros2_universal_robot/resource/Universal_Robots_ROS2_Driver/ur_description/config/ur5e/visual_parameters.yaml
webots_ros2_universal_robot/resource/robotiq/robotiq_3f_gripper_visualization/cfg/robotiq-3f-gripper_articulated_macro.xacro
webots_ros2_universal_robot/resource/robotiq/robotiq_3f_gripper_visualization/cfg/robotiq-3f-gripper_finger_articulated_macro.xacro

Fixes #558 and #581.
URDFs can be spawned in 2 different ways:
- By giving the complete robot description and the path to the resources as a prefix to append to assets relative URLs.
- By giving only the path to the URDF file.
The first way was correctly handled on WSL and macOS. The second one was not and is trickier, as the path must be kept to open the file on the Linux side, while the URL should be edited to be compatible with WSL and the shared directory, respectively on Windows and macOS.
To counter this problem, on Windows and macOS, the URDF file is opened by the `ROS2_supervisor` and is passed as the robot description, and the path prefix is set according to the URDF path by searching for the 'share' directory.
The URL edition is now completely done in the supervisor, for …

Fix URDF spawner on macOS and WSL

---

webots_ros2_tests/test/test_system_driver.py

The CI tests are not working because the ROS2 supervisor was not correctly started in one of the tests.

Fix CI tests

---

scripts/sync_controller_lib.sh

With the update of the libController (https://github.com/cyberbotics/webots/pull/5896) to check the version against the one from Webots, the `version.txt` file is needed for compilation.

Update sync_controller_lib.sh to copy version.txt

---

webots_ros2_epuck/resource/ros2_control.yml
webots_ros2_tiago/resource/ros2_control.yml
webots_ros2_turtlebot/resource/ros2control.yml

Fix #593 caused by an update of `diff_drive_controller`.
This can be reverted once version `2.16.0` of the package is available.

Temporarily fix `diff_drive controller` bad variable name

---

webots_ros2/CHANGELOG.rst
webots_ros2_driver/CHANGELOG.rst
webots_ros2_driver/webots_ros2_driver/utils.py
webots_ros2_driver/webots_ros2_driver/webots_launcher.py

The webots driver launcher do not offer the possibility to set the streaming port. this prevents the use in multi user environments where every user wants to see its own simulation.
Moreover, the launcher only copies the world file and ignores the world project file. Therefore, custom settings (e.g. optional renderings are ignored).
This pull request adds a parameter to webots launcher constructor to set the port. The default parameter setting is set to the default port 1234. Therefore, there should not be any difference for existing setups.
Moreover, the copy of the world project file is added. The execute()-Function searches if a .wbproj file with the same name as the world file exists and then copies it to the location of the temporary world file. When webots starts, it …

Adding port parameter and usage of webots world project file to launcher.py

---

webots_ros2_turtlebot/resource/ros2control.yml

The wheel_separation param in ros2control.yml is incorrect, which would make the odometry not accurate.
While the wheel_separation is set to 1.60, when making the robot to turn and the odometry records 360 degrees, the orientation of the robot in webots is not matched with the odometry.
The initial orientation is shown in the picture below:
After making a 360 degree turn in odometry, the orientation is shown below:
I found that the cause of the problem is related to the wheel_separation parameter. In the "TurtleBot3Burger.proto" file, the position of the left joint is "0 0.08 0.033", and the right joint is "0 -0.08 0.033". So it seems that the separation is 0.16. But that does not take the wheel cylinder into account. The height of the cylinder is 0.018, so the actual …

Fix ros2_control wheel_separation param for turtlebot3

---

.github/workflows/test.yml
scripts/ci_after_init.bash
scripts/ci_before_init_embed.bash

Nav2 random failures in the TIAGo tests are due to issues with the default Fast DDS on Humble. See https://github.com/ros-planning/navigation2/issues/3033#issuecomment-1457854463 comment and issue.
We switch the DDS to Cyclone to fix the problem.

Fix random Nav2 failure with Fast DDS

---

webots_ros2_tiago/resource/ros2_control.yml
webots_ros2_turtlebot/resource/ros2control.yml

Based on https://github.com/cyberbotics/webots_ros2/pull/676#discussion_r1140120581, it is cleaner to define the correct parameters for wheel separation and wheel radius. The multiplier parameter allows to adjust the parameter at runtime to obtain optimal odometry.

Cleaner ros2_control parameters

---

webots_ros2/CHANGELOG.rst
webots_ros2_epuck/CHANGELOG.rst
webots_ros2_epuck/launch/robot_launch.py

With the previous e-puck fix (#694), it was not possible to launch RViz from the main launch file without the Navigation or Mapping tool. RViz can still be used alone for odometry visualization for example. This PR cleans up the way tools are launched.

Cleanup e-puck tools to run RViz alone

---

webots_ros2/CHANGELOG.rst
webots_ros2_driver/CHANGELOG.rst
webots_ros2_driver/CMakeLists.txt
webots_ros2_driver/include/webots_ros2_driver/WebotsNode.hpp
webots_ros2_driver/src/PythonPlugin.cpp
webots_ros2_driver/src/WebotsNode.cpp
webots_ros2_driver/webots_ros2_driver/utils.py
webots_ros2_driver/webots_ros2_driver/webots_controller.py
webots_ros2_epuck/CHANGELOG.rst
webots_ros2_epuck/launch/robot_launch.py
webots_ros2_mavic/CHANGELOG.rst
webots_ros2_mavic/launch/robot_launch.py
webots_ros2_tesla/CHANGELOG.rst
webots_ros2_tesla/launch/robot_launch.py
webots_ros2_tests/CHANGELOG.rst
webots_ros2_tests/test/test_system_driver.py
webots_ros2_tiago/CHANGELOG.rst
webots_ros2_tiago/launch/robot_bringup_launch.py
webots_ros2_tiago/launch/robot_launch.py
webots_ros2_turtlebot/CHANGELOG.rst
webots_ros2_turtlebot/launch/robot_launch.py
webots_ros2_universal_robot/CHANGELOG.rst
webots_ros2_universal_robot/launch/multirobot_launch.py
webots_ros2_universal_robot/launch/robot_launch/robot_nodes_launch.py

New WebotsController node that starts the webots-controller launcher to setup the correct environment variables and start the Driver interface node.

Feature WebotsController node

---

webots_ros2/CHANGELOG.rst
webots_ros2_epuck/CHANGELOG.rst
webots_ros2_epuck/launch/robot_launch.py
webots_ros2_mavic/CHANGELOG.rst
webots_ros2_mavic/launch/robot_launch.py
webots_ros2_tesla/CHANGELOG.rst
webots_ros2_tesla/launch/robot_launch.py
webots_ros2_tiago/CHANGELOG.rst
webots_ros2_tiago/launch/robot_launch.py
webots_ros2_turtlebot/CHANGELOG.rst
webots_ros2_turtlebot/launch/robot_launch.py
webots_ros2_universal_robot/CHANGELOG.rst
webots_ros2_universal_robot/launch/multirobot_launch.py

Follow-up to conclusions in #655.
- `webots_ros2_mavic` and `webots_ros2_tesla` can be simplified to benefit from the `respawn` parameter.
- `webots_ros2_epuck`, `webots_ros2_tiago` and `webots_ros2_turtlebot` are cleaned-up to remove the reset functionality, as there is no clear solution to restart nav2 and rviz nodes. The manual solution with multiple launch files is documented in #655 but won't be implemented in the package. However, it will also be documented in a new tutorial in the official ROS documentation on how to handle the reset button depending on the nodes of the package.
- `webots_ros2_universal_robot` is also dadapted for consistency.

Cleanup simulation reset in launch files

---

webots_ros2/CHANGELOG.rst
webots_ros2_control/CHANGELOG.rst
webots_ros2_control/src/Ros2Control.cpp

The activation of all components has been deprecated from version 3.15.0 of hardware_interface. It is replaced by manual activation.
This was reported in https://github.com/ros/rosdistro/pull/37344#issuecomment-1609109208.

Fix ros2 control hardware interface API update

---

webots_ros2_driver/webots_ros2_driver/ros2_supervisor.py
webots_ros2_driver/webots_ros2_driver/urdf_spawner.py

For a clearer robot format support, the URDF/Xacro format is now deprecated and will no longer be supported. Instead, robots must be declared directly as PROTO files in the world file. They can still be imported on the fly using the robot string importer and the Ros2Supervisor.
Projects using URDF/Xacro robots can be converted manually to PROTO using the urdf2webots converter.
A new PROTO Spawner will be implemented in the develop branch.

Deprecate URDF Spawner

---

webots_ros2_driver/webots_ros2_driver/ros2_supervisor.py

Current deprecation message lacks clarity and suggests to use the PROTOSpawner which has not been implemented yet.

Improve URDFSpawner deprecation message

---

webots_ros2_driver/webots_ros2_driver/ros2_supervisor.py

While writing the `Ros2Supervisor` [tutorial](https://github.com/cyberbotics/ros2_documentation/pull/18), I came across some bugs in the import and remove functions of the supervisor node.
The name of the imported nodes should be able to contain capital letters and the remove function was not deleting the correct node in some scenarios.

Fix Ros2Supervisor import and remove node strings

---

webots_ros2_driver/src/WebotsNode.cpp
webots_ros2_universal_robot/launch/robot_launch/robot_moveit_nodes_launch.py
webots_ros2_universal_robot/launch/robot_launch/robot_nodes_launch.py

follow up to https://github.com/cyberbotics/webots_ros2/commit/f3045ad16c6c41b0edbf845f06391be5d0990022
robot state publisher's robot_description update service doesn't get called, and also doesn't subscribe to joint_states' topic, because of the namespace 'ur5e' added to the WebotsController
add remappings to the robot state publisher node to fix it
- webots_ros2_universal_robot

add remappings to robot state publisher for ur5e example

---

webots_ros2_control/src/Ros2Control.cpp

Fix #881 
Latest version of `hardware_interface` on Rolling is `4.2.0`

Fix version check for hardware_interface

---

webots_ros2_control/src/Ros2Control.cpp

Backport of https://github.com/cyberbotics/webots_ros2/pull/882

Fix hw interface check

---

webots_ros2_driver/scripts/webots_tcp_client.py
webots_ros2_driver/webots_ros2_driver/utils.py

This PR fixes a bug preventing `webots_ros2_driver` nodes running in a Docker image from launching and connecting to Webots running on a macOS host. The change set includes a new `is_docker()` function that checks if the process is running in an image. If so, the `get_host_ip()` will return `host.docker.internal`, [Docker's special DNS name](https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host) that resolves to the host's IP address.
Closes #888 
- `webots_ros2_driver`
**Tasks**
I modeled the changes off the `is_wsl()` function; however, WSL has tighter integration with its host (Windows) than Docker Desktop. Docker and virtual …

Fix host IP address resolution for nodes running in Docker

---

webots_ros2_control/src/Ros2Control.cpp

it's probably needed after https://github.com/ros-controls/ros2_control/commit/385293e5d0626c57636a05c66de4380fcfd5bee7
fixes https://github.com/cyberbotics/webots_ros2/issues/893
After, https://github.com/ros-controls/ros2_control/commit/385293e5d0626c57636a05c66de4380fcfd5bee7, init_services() won't be called unless is_urdf_loaded__ is set to true. Passing robot description again led to controller name duplicate error.
This pull-request fixes issue https://github.com/cyberbotics/webots_ros2/issues/893
**Tasks**

set is_urdf_loaded__ of the resource manager to true

---

webots_ros2_control/src/Ros2Control.cpp

Quick bugfix for #896, which doesn't work for `iron` or `rolling` because they use a `ros2_control` hardware interface version  `>3.15`. For some reason still fails for `rolling`. 

Fixed #896 so it works for ROS2 Iron.

---

webots_ros2_epuck/launch/robot_launch.py
webots_ros2_tests/test/test_system_epuck.py
webots_ros2_tests/test/test_system_turtlebot.py
webots_ros2_tiago/launch/robot_launch.py
webots_ros2_turtlebot/launch/robot_launch.py

https://github.com/ros-controls/ros2_controllers/pull/812
- webots_ros2_tiago
- webots_ros2_turtlebot
**Tasks**

unstamped cmd_vel option is removed

---

scripts/ci_after_init.bash
webots_ros2_driver/CMakeLists.txt

Rolling is switched to ubuntu 24
**Tasks**
With python3.12, missing_whitespace_around_operator is not available in pycodestyle
https://github.com/PyCQA/flake8/commit/9786562feb573d30c73f18e1a0a6685c8584e9b5

build and pass tests for ros2 rolling

---

webots_ros2_tests/test/test_system_turtlebot_tutorial_navigation.py

the nav2 turtlebot test fails many-a-times.
- webots_ros2_tests
**Tasks**

webots_ros2_tests: wait for 10 secs before sending nav2 goal

---

webots_ros2/CHANGELOG.rst
webots_ros2/package.xml
webots_ros2/setup.py
webots_ros2_control/package.xml
webots_ros2_driver/package.xml
webots_ros2_epuck/package.xml
webots_ros2_epuck/setup.py
webots_ros2_importer/package.xml
webots_ros2_importer/setup.py
webots_ros2_mavic/package.xml
webots_ros2_mavic/setup.py
webots_ros2_msgs/package.xml
webots_ros2_tesla/package.xml
webots_ros2_tesla/setup.py
webots_ros2_tests/package.xml
webots_ros2_tests/setup.py
webots_ros2_tiago/package.xml
webots_ros2_tiago/setup.py
webots_ros2_turtlebot/package.xml
webots_ros2_turtlebot/setup.py
webots_ros2_universal_robot/CHANGELOG.rst
webots_ros2_universal_robot/package.xml
webots_ros2_universal_robot/setup.py

This PR performs version upgrade to 2023.1.2.
This PR should also update changelogs release dates for version 2023.1.2 once #837 is merged. #770 is targeting develop and will be released under 2024.0.0, so it doesn't constraint this release.
Once merged the release procedure can be followed from [section Tag](https://github.com/cyberbotics/webots_ros2/wiki/Internal-Publishing#tag).

Prepare for version 2023.1.2

---

webots_ros2_control/src/Ros2ControlSystem.cpp

If the `initial_value` param in the position `state_interface` URDF is set, then the robot joint will move to that position when Webots starts.
Currently uses `wb_motor_set_position` which means the robot will start at zero and instantly move once Webots finishes loading. Tried to implement the same behavior using `wb_supervisor_node_set_joint_position` but with no success.

Webots now handles initial_value params in position state_interface.

---

webots_ros2_control/CHANGELOG.rst
webots_ros2_control/src/Ros2ControlSystem.cpp

I noticed that the sign of the acceleration was reversed.

Update Ros2ControlSystem.cpp: correct joint.acceleration

---

webots_ros2_control/src/Ros2Control.cpp
webots_ros2_driver/CMakeLists.txt

This adds a guard condition to `Ros2Control::step()` to check node clock is not zero, fixes the "No clock received" error. Basically stops a step update occurring unless the clock is not zero.

Guard condition to check node clock is not zero, to suppress "No clock received" error from ros2_control.

---

webots_ros2_control/include/webots_ros2_control/Ros2ControlSystem.hpp
webots_ros2_control/src/Ros2Control.cpp
webots_ros2_control/src/Ros2ControlSystem.cpp

Signed-off-by: soham2560
There is a Build Error for webots_ros2_control on Rolling as described in #1041. Seems to be from the recent update to 5.0.0 and above for versions (refer https://github.com/ros-controls/ros2_control/commit/151b22ee7bbc9056cfd7df1a935b024e60b5b687)
After some thought, have decided to also add support for ver5.3 here, as it introduces updated API.
- refer [added ver5.3 support](https://github.com/cyberbotics/webots_ros2/pull/1042/commits/5301dd9f1e349c7eda5bed1516bd617c644a3d85) for changes made
This pull-request fixes issue #1041

Added hardware_interface ver 5.x.x support
