cyberbotics/webots_ros2

- .travis.yml
- webots_ros2_core/webots_ros2_core/utils.py
- webots_ros2_examples/launch/example.launch.py
- webots_ros2_examples/webots_ros2_examples/example_controller.py
- webots_ros2_universal_robot/launch/universal_robot.launch.py
- webots_ros2_universal_robot/webots_ros2_universal_robot/universal_robot.py
This PR adds the possibility to retrieve the version of Webots from ROS and adds a module to manage paths (to remove code duplication).
> Add Webots version function and module to manage pathes

- webots_ros2_core/CHANGELOG.rst
- webots_ros2_core/webots_ros2_core/webots_node.py
- webots_ros2_examples/webots_ros2_examples/example_controller.py
- webots_ros2_universal_robot/CHANGELOG.rst
- webots_ros2_universal_robot/launch/universal_robot_multiple.launch.py
- webots_ros2_universal_robot/setup.py
- webots_ros2_universal_robot/webots_ros2_universal_robot/universal_robot.py
- webots_ros2_universal_robot/worlds/universal_robot_multiple.wbt
> Add support for multiple robots.

- README.md
- webots_ros2_core/webots_ros2_core/utils.py
- webots_ros2_core/webots_ros2_core/webots_launcher.py
Improve support of Windows.
Doc updated too: http://wiki.ros.org/webots_ros2#From_Sources
> Extend Windows Support

- .github/FUNDING.yml
- .travis.yml
- CONTRIBUTING.md
- README.md
- webots_ros2_core/CHANGELOG.rst
- webots_ros2_core/webots_ros2_core/utils.py
- webots_ros2_core/webots_ros2_core/webots_launcher.py
- webots_ros2_core/webots_ros2_core/webots_node.py
- webots_ros2_examples/webots_ros2_examples/example_controller.py
- webots_ros2_universal_robot/CHANGELOG.rst
- webots_ros2_universal_robot/launch/universal_robot_multiple.launch.py
- webots_ros2_universal_robot/setup.py
- webots_ros2_universal_robot/webots_ros2_universal_robot/universal_robot.py
- webots_ros2_universal_robot/worlds/universal_robot_multiple.wbt
> Merge Master into Crystal

- webots_ros2_core/webots_ros2_core/joint_state_publisher.py
- webots_ros2_core/webots_ros2_core/webots_node.py
- webots_ros2_examples/webots_ros2_examples/example_controller.py
- webots_ros2_universal_robot/webots_ros2_universal_robot/universal_robot.py
Some function arguments are not available in Crystal.
Fix #20
> Fix crystal compatibility issues

- .travis.yml
The `control_msgs` package is now available on Dashing :smiley:
> Activate Dashing Test

- webots_ros2_core/webots_ros2_core/trajectory_follower.py
- webots_ros2_universal_robot/CHANGELOG.rst
> Fixed Universal Robot Action Manager

- .github/FUNDING.yml
> Add sponsoring

- webots_ros2_core/webots_ros2_core/webots_launcher.py
The goal of this PR is to render these packages compatible with the AWS RoboMaker.
> Add AWS RobotMaker Support

- .travis.yml
> Add Eloquent to Release

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- CODE_OF_CONDUCT.md
Add all the missing item listed in https://github.com/cyberbotics/webots_ros2/community
> Add Issues/PR templates + Code of conduct

- .travis.yml
- webots_ros2_abb/worlds/abb_irb4600.wbt
- webots_ros2_core/CHANGELOG.rst
- webots_ros2_core/webots_ros2_core/tf_publisher.py
- webots_ros2_core/webots_ros2_core/webots_node.py
- webots_ros2_demos/worlds/armed_robots.wbt
- webots_ros2_examples/worlds/ros_example.wbt
- webots_ros2_universal_robot/launch/universal_robot_rviz.launch.py
- webots_ros2_universal_robot/worlds/universal_robot.wbt
- webots_ros2_universal_robot/worlds/universal_robot_multiple.wbt
This PR uses cyberbotics/webots#1331 to make the TF publisher more generic and functionnal with PROTO nodes too.
> Generalize TF Publisher

- webots_ros2_core/webots_ros2_core/webots_launcher.py
Fix the launch problem due to missing argument.
- `webots_ros2_core`
> Test webots_ros2 package with Eloquent distribution

- .travis.yml
- webots_ros2_epuck/launch/robot_tools_launch.py
- webots_ros2_epuck/package.xml
- webots_ros2_importer/webots_ros2_importer/urdf2proto.py
This PR removes the test on Dashin (we decided to not support it anymore) and add tests for Foxy instead.
> Update Tests to Foxy

- webots_ros2_core/webots_ros2_core/webots_differential_drive_node.py
This lines were causing division by 0 at the first step.
> Fix division by 0

- webots_ros2_core/webots_ros2_core/devices/device_manager.py
- webots_ros2_core/webots_ros2_core/devices/imu_device.py
- webots_ros2_core/webots_ros2_core/devices/sensor_device.py
- webots_ros2_epuck/webots_ros2_epuck/driver.py
This PR wraps Webots' Accelerometer, Gyro and InertialUnit to create Imu topic.
**Tasks**
> Add Imu ROS2 Wrapper

- README.md
> Add ROSIN Acknowledgement

- .travis.yml
- webots_ros2_importer/package.xml
This optional dependency is only available on version >= Foxy
> Add Foxy Optional Dependency

- .github/workflows/python-publish.yml
Automatic bloom-release on release creation.
> Add bloom-release workflow

- .github/workflows/bloom-release.yml
Rename the file and hopefully (there is unfortunately now way to test before merging to master) fix https://github.com/cyberbotics/webots_ros2/runs/833657511?check_suite_focus=true#step:3:39
> Fix bloom release workflow

- .github/workflows/bloom-release.yml
This fixes the undefined 'version' variable (https://github.com/cyberbotics/webots_ros2/runs/833697424?check_suite_focus=true#step:3:39).
> Fix (again) bloom release workflow

- webots_ros2_desktop/setup.py
> Update Repo Path

- webots_ros2/CHANGELOG.rst
- webots_ros2_core/webots_ros2_core/utils.py
- webots_ros2_desktop/setup.py
This PR fixes various issues with the packages on macOS.
> Various macOS fixes

- webots_ros2_importer/CHANGELOG.rst
- webots_ros2_importer/webots_ros2_importer/urdf2proto.py
- webots_ros2_importer/webots_ros2_importer/xacro2proto.py
Update submodule reference and handle new arguments
> Update urdf2webots submodule

- webots_ros2_examples/webots_ros2_examples/khepera_driver.py
> Fix Classname

- .github/workflows/test.yml
- webots_ros2_desktop/setup.py
This PR uses Github Action to perform extended tests (includes the webots_ros2_desktop package too).
> Add Github Actions

- webots_ros2/package.xml
- webots_ros2/setup.py
- webots_ros2_abb/package.xml
- webots_ros2_abb/setup.py
- webots_ros2_core/CHANGELOG.rst
- webots_ros2_core/package.xml
- webots_ros2_core/setup.py
- webots_ros2_demos/package.xml
- webots_ros2_demos/setup.py
- webots_ros2_epuck/package.xml
- webots_ros2_epuck/setup.py
- webots_ros2_examples/package.xml
- webots_ros2_examples/setup.py
- webots_ros2_importer/package.xml
- webots_ros2_importer/setup.py
- webots_ros2_msgs/package.xml
- webots_ros2_tiago/package.xml
- webots_ros2_tiago/setup.py
- webots_ros2_universal_robot/package.xml
- webots_ros2_universal_robot/setup.py
- webots_ros2_ur_e_description/package.xml
- webots_ros2_ur_e_description/setup.py
Updates version number from 1.0.1 to 1.0.2
> Update version number to 1.0.2

- webots_ros2_ur_e_description/README.md
- webots_ros2_ur_e_description/package.xml
> Fix ur_e_description Attribution

- .github/workflows/test.yml
- webots_ros2_core/webots_ros2_core/webots_launcher.py
The introduction window forbids the simulation to start properly during the first run
> Hide introduction window

- webots_ros2/webots_ros2/__init__.py
- webots_ros2_abb/launch/abb_irb4600.launch.py
- webots_ros2_core/webots_ros2_core/__init__.py
- webots_ros2_core/webots_ros2_core/joint_state_publisher.py
- webots_ros2_core/webots_ros2_core/math/__init__.py
- webots_ros2_core/webots_ros2_core/tf_publisher.py
- webots_ros2_core/webots_ros2_core/trajectory_follower.py
- webots_ros2_core/webots_ros2_core/utils.py
- webots_ros2_core/webots_ros2_core/webots_launcher.py
- webots_ros2_core/webots_ros2_core/webots_node.py
- webots_ros2_demos/launch/armed_robots.launch.py
- webots_ros2_demos/webots_ros2_demos/__init__.py
- webots_ros2_demos/webots_ros2_demos/armed_robots_abb.py
- webots_ros2_demos/webots_ros2_demos/armed_robots_ur.py
- webots_ros2_demos/webots_ros2_demos/follow_joint_trajectory_client.py
- webots_ros2_examples/launch/example.launch.py
- webots_ros2_examples/webots_ros2_examples/__init__.py
- webots_ros2_examples/webots_ros2_examples/example_controller.py
- webots_ros2_importer/webots_ros2_importer/__init__.py
- webots_ros2_importer/webots_ros2_importer/urdf2proto.py
- webots_ros2_importer/webots_ros2_importer/xacro2proto.py
- webots_ros2_universal_robot/launch/universal_robot.launch.py
- webots_ros2_universal_robot/launch/universal_robot_multiple.launch.py
- webots_ros2_universal_robot/launch/universal_robot_rviz.launch.py
- webots_ros2_ur_e_description/launch/ur5e_state_publisher.launch.py
- webots_ros2_ur_e_description/webots_ros2_ur_e_description/__init__.py
Develop branch should target R2021a. Also, copyright was wrong in the headers
> Increase version number

- .github/workflows/test.yml
- webots_ros2_core/CHANGELOG.rst
- webots_ros2_core/webots_ros2_core/devices/lidar_device.py
- webots_ros2_core/webots_ros2_core/utils.py
Here we try to utilize new `getPointCloud(dtype='buffer')` (https://github.com/cyberbotics/webots/pull/2321) to increase performance of the LiDAR.
- https://github.com/cyberbotics/webots/issues/2283
- https://answers.ros.org/question/362928/publishreceive-large-pointcloud2-is-very-slow/
**Tasks**
**Tests**
```bash
ros2 launch webots_ros2_core robot_launch.py \
executable:=webots_robotic_arm_node \
world:=$(ros2 pkg prefix webots_ros2_universal_robot --share)/worlds/universal_robot_lidar.wbt
```
> Upgrade PointCloud to PointCloud2

- .github/workflows/test.yml
- .travis.yml
- webots_ros2_core/launch/robot_launch.py
- webots_ros2_demos/launch/armed_robots.launch.py
- webots_ros2_epuck/launch/rats_life_waypoints_launch.py
- webots_ros2_epuck/launch/robot_tools_launch.py
- webots_ros2_examples/launch/example.launch.py
- webots_ros2_importer/package.xml
- webots_ros2_tiago/launch/tiago.launch.py
- webots_ros2_universal_robot/launch/universal_robot_multiple.launch.py
- webots_ros2_universal_robot/launch/universal_robot_rviz.launch.py
- webots_ros2_universal_robot/launch/universal_robot_rviz_dynamic.launch.py
- webots_ros2_ur_e_description/launch/ur5e_state_publisher.launch.py
Since Foxy is currently the only supported distribution (and soon Rolling) we can rid of the node_executable deprecation warnings in the master branch.
> Merge `foxy` to `master` 

- webots_ros2/package.xml
This will install `webots_ros2_turtlebot` and `webots_ros2_tutorials` automatically once user installs the `webots_ros2` package.
> Add `turtlebot` and `tutorials` as dependencies

- webots_ros2/package.xml
- webots_ros2/setup.py
- webots_ros2_abb/package.xml
- webots_ros2_abb/setup.py
- webots_ros2_core/package.xml
- webots_ros2_core/setup.py
- webots_ros2_demos/package.xml
- webots_ros2_demos/setup.py
- webots_ros2_epuck/package.xml
- webots_ros2_epuck/setup.py
- webots_ros2_examples/package.xml
- webots_ros2_examples/setup.py
- webots_ros2_importer/package.xml
- webots_ros2_importer/setup.py
- webots_ros2_msgs/package.xml
- webots_ros2_tiago/package.xml
- webots_ros2_tiago/setup.py
- webots_ros2_turtlebot/package.xml
- webots_ros2_turtlebot/setup.py
- webots_ros2_tutorials/package.xml
- webots_ros2_tutorials/setup.py
- webots_ros2_universal_robot/package.xml
- webots_ros2_universal_robot/setup.py
- webots_ros2_ur_e_description/package.xml
- webots_ros2_ur_e_description/setup.py
> Update version number in preparation of the next release

- README.md
> Add OpenDR project acknowledgement

- webots_ros2_core/webots_ros2_core/devices/device_manager.py
- webots_ros2_core/webots_ros2_core/devices/gps_device.py
Add GPS device for webots_ros2 API. 
You can test it by adding:
```
GPS {
accuracy 0.5
speedNoise 2
}
```
In the tesla model and creating a subscriber type `PointStamped`, topic `gps/gps`
> add gps_device

- webots_ros2_importer/package.xml
Follow up on https://github.com/cyberbotics/urdf2webots/pull/116
> Switch from pep8 to pycodestyle

- webots_ros2_turtlebot/package.xml
- webots_ros2_turtlebot/resource/ros2control.yml
See https://github.com/cyberbotics/webots_ros2/pull/221#issuecomment-855821948
> Add missing dependency to TurtleBot3 Burger

- webots_ros2/package.xml
- webots_ros2/setup.py
- webots_ros2_abb/package.xml
- webots_ros2_abb/setup.py
- webots_ros2_control/package.xml
- webots_ros2_core/package.xml
- webots_ros2_core/setup.py
- webots_ros2_demos/package.xml
- webots_ros2_demos/setup.py
- webots_ros2_driver/README.md
- webots_ros2_driver/package.xml
- webots_ros2_epuck/package.xml
- webots_ros2_epuck/setup.py
- webots_ros2_examples/package.xml
- webots_ros2_examples/setup.py
- webots_ros2_importer/package.xml
- webots_ros2_importer/setup.py
- webots_ros2_msgs/package.xml
- webots_ros2_tesla/package.xml
- webots_ros2_tesla/setup.py
- webots_ros2_tiago/package.xml
- webots_ros2_tiago/setup.py
- webots_ros2_turtlebot/package.xml
- webots_ros2_turtlebot/setup.py
- webots_ros2_tutorials/package.xml
- webots_ros2_tutorials/setup.py
- webots_ros2_universal_robot/package.xml
- webots_ros2_universal_robot/setup.py
- webots_ros2_ur_e_description/package.xml
- webots_ros2_ur_e_description/setup.py
This PR increases the version number (prepares for the next release) and adds documentation for `webots_ros2_driver`
> Increase version and add documentation

- webots_ros2_epuck/protos/E-puck_enu.proto
- webots_ros2_epuck/protos/LegoTallInterval.proto
- webots_ros2_epuck/protos/LegoTallWall.proto
- webots_ros2_examples/protos/Khepera4_enu.proto
- webots_ros2_tesla/worlds/tesla_world.wbt
> update to R2021b

- webots_ros2_driver/CMakeLists.txt
> Fix library directory

- webots_ros2_driver/CMakeLists.txt
> Fix the IMU library exportation

- webots_ros2_core/webots_ros2_core/devices/camera_device.py
- webots_ros2_core/webots_ros2_core/devices/distance_sensor_device.py
- webots_ros2_core/webots_ros2_core/devices/gps_device.py
- webots_ros2_core/webots_ros2_core/devices/imu_device.py
- webots_ros2_core/webots_ros2_core/devices/led_device.py
- webots_ros2_core/webots_ros2_core/devices/lidar_device.py
- webots_ros2_core/webots_ros2_core/devices/light_sensor_device.py
- webots_ros2_core/webots_ros2_core/devices/range_finder_device.py
- webots_ros2_core/webots_ros2_core/devices/robot_device.py
- webots_ros2_core/webots_ros2_core/devices/sensor_device.py
- webots_ros2_core/webots_ros2_core/joint_state_publisher.py
- webots_ros2_core/webots_ros2_core/webots_differential_drive_node.py
- webots_ros2_core/webots_ros2_core/webots_node.py
- webots_ros2_core/webots_ros2_core/webots_robotic_arm_node.py
Fix the errors showing when running `colcon test` due to pep257 convention
This pull-request fixes issue #288 
**Tasks**
> Fix to suit to pep257 convention

- webots_ros2_importer/webots_ros2_importer/xacro2proto.py
Compatibility with `urdf2webots` regarding the `--input` syntax.
-
- webots_ros2_importer
> Add keyword input file argument

- webots_ros2/package.xml
- webots_ros2/setup.py
- webots_ros2_control/CHANGELOG.rst
- webots_ros2_control/package.xml
- webots_ros2_core/package.xml
- webots_ros2_core/setup.py
- webots_ros2_driver/package.xml
- webots_ros2_epuck/package.xml
- webots_ros2_epuck/setup.py
- webots_ros2_importer/package.xml
- webots_ros2_importer/setup.py
- webots_ros2_mavic/package.xml
- webots_ros2_mavic/setup.py
- webots_ros2_msgs/package.xml
- webots_ros2_tesla/package.xml
- webots_ros2_tesla/setup.py
- webots_ros2_tests/package.xml
- webots_ros2_tests/setup.py
- webots_ros2_tiago/package.xml
- webots_ros2_tiago/setup.py
- webots_ros2_turtlebot/package.xml
- webots_ros2_turtlebot/setup.py
- webots_ros2_universal_robot/package.xml
- webots_ros2_universal_robot/setup.py
This prepare the version 1.1.3 that aims to fix the building failure on the ROS2 buildfarm for `Foxy`.
> version-1.1.3 ready

- webots_ros2/package.xml
- webots_ros2/setup.py
- webots_ros2_control/CHANGELOG.rst
- webots_ros2_control/package.xml
- webots_ros2_core/package.xml
- webots_ros2_core/setup.py
- webots_ros2_driver/package.xml
- webots_ros2_epuck/package.xml
- webots_ros2_epuck/setup.py
- webots_ros2_importer/package.xml
- webots_ros2_importer/setup.py
- webots_ros2_mavic/package.xml
- webots_ros2_mavic/setup.py
- webots_ros2_msgs/package.xml
- webots_ros2_tesla/package.xml
- webots_ros2_tesla/setup.py
- webots_ros2_tests/package.xml
- webots_ros2_tests/setup.py
- webots_ros2_tiago/package.xml
- webots_ros2_tiago/setup.py
- webots_ros2_turtlebot/package.xml
- webots_ros2_turtlebot/setup.py
- webots_ros2_universal_robot/package.xml
- webots_ros2_universal_robot/setup.py
**List of conflicts**
All the 24 changed files for the version `1.1.3`
> Merge master into foxy

- webots_ros2_tests/test/test_system_tiago.py
- webots_ros2_tests/test/test_system_turtlebot_tutorial_navigation.py
- webots_ros2_tests/test/test_system_turtlebot_tutorial_slam.py
Create a system test for the tutorial `Navigation` for `Turtlebot3`.
Also rename `test_system_turtlebot_tutorials` in `test_system_turtlebot_tutorial_slam`.
> Creation of a system test for turtlebot3 navigation tutorial

- webots_ros2_driver/CMakeLists.txt
> Remove double `webots_ros2_driver` header installation

- webots_ros2_driver/webots_ros2_driver/webots_launcher.py
- webots_ros2_universal_robot/launch/multirobot_launch.py
- webots_ros2_universal_robot/webots_ros2_universal_robot/abb_controller.py
- webots_ros2_universal_robot/webots_ros2_universal_robot/follow_joint_trajectory_client.py
- webots_ros2_universal_robot/webots_ros2_universal_robot/ur5e_controller.py
This PR is to solved the time to time failing of the `universal_robot` system test in the CI.
This pull-request fixes issue #310
> Remove sleep() for universal robot

- webots_ros2_turtlebot/launch/robot_launch.py
> Delete the `controller_manager` timeout workaround

- scripts/ci_after_init.bash
- webots_ros2_control/CHANGELOG.rst
- webots_ros2_driver/CHANGELOG.rst
- webots_ros2_epuck/CHANGELOG.rst
- webots_ros2_mavic/CHANGELOG.rst
- webots_ros2_tesla/CHANGELOG.rst
- webots_ros2_tests/CHANGELOG.rst
- webots_ros2_tiago/CHANGELOG.rst
- webots_ros2_universal_robot/CHANGELOG.rst
In order to prepare the `1.2.0` release I updated the `CHANGELOG` files.
> Changelogs update version 1.2.0

- webots_ros2/package.xml
- webots_ros2/setup.py
- webots_ros2_control/package.xml
- webots_ros2_core/package.xml
- webots_ros2_core/setup.py
- webots_ros2_driver/CHANGELOG.rst
- webots_ros2_driver/package.xml
- webots_ros2_epuck/package.xml
- webots_ros2_epuck/setup.py
- webots_ros2_importer/package.xml
- webots_ros2_importer/setup.py
- webots_ros2_mavic/package.xml
- webots_ros2_mavic/setup.py
- webots_ros2_msgs/package.xml
- webots_ros2_tesla/package.xml
- webots_ros2_tesla/setup.py
- webots_ros2_tests/CHANGELOG.rst
- webots_ros2_tests/package.xml
- webots_ros2_tests/setup.py
- webots_ros2_tiago/package.xml
- webots_ros2_tiago/setup.py
- webots_ros2_turtlebot/CHANGELOG.rst
- webots_ros2_turtlebot/package.xml
- webots_ros2_turtlebot/setup.py
- webots_ros2_universal_robot/package.xml
- webots_ros2_universal_robot/setup.py
Prepare releases to fix the lidar.
> Prepare version 1.2.1

- webots_ros2/package.xml
- webots_ros2/setup.py
- webots_ros2_control/package.xml
- webots_ros2_core/package.xml
- webots_ros2_core/setup.py
- webots_ros2_driver/CHANGELOG.rst
- webots_ros2_driver/package.xml
- webots_ros2_epuck/package.xml
- webots_ros2_epuck/setup.py
- webots_ros2_importer/package.xml
- webots_ros2_importer/setup.py
- webots_ros2_mavic/package.xml
- webots_ros2_mavic/setup.py
- webots_ros2_msgs/package.xml
- webots_ros2_tesla/package.xml
- webots_ros2_tesla/setup.py
- webots_ros2_tests/package.xml
- webots_ros2_tests/setup.py
- webots_ros2_tiago/package.xml
- webots_ros2_tiago/setup.py
- webots_ros2_turtlebot/package.xml
- webots_ros2_turtlebot/setup.py
- webots_ros2_universal_robot/CHANGELOG.rst
- webots_ros2_universal_robot/package.xml
- webots_ros2_universal_robot/setup.py
Prepare new releases to fix the `MoveIt` dependency.
> Prepare version 1.2.2

- scripts/ci_after_init.bash
- scripts/ci_before_init_embed.bash
> Merge mast into develop

- scripts/ci_after_init.bash
- webots_ros2_tiago/package.xml
- webots_ros2_turtlebot/package.xml
- webots_ros2_turtlebot/webots_ros2_turtlebot/plugin_example.py
> Merge master into develop

- webots_ros2_driver/include/webots_ros2_driver/plugins/static/Ros2Camera.hpp
- webots_ros2_driver/src/plugins/static/Ros2Camera.cpp
The camera was not enabling the recognition in case of subscriptions and was not clearing the lists of the messages.
This pull-request fixes issue #393.
> Fix recognition camera

- webots_ros2_mavic/setup.py
- webots_ros2_tesla/setup.py
- webots_ros2_turtlebot/webots_ros2_turtlebot/plugin_example.py
The [Python plugin tutorial](https://github.com/cyberbotics/webots_ros2/wiki/Tutorial-Creating-a-Custom-Python-Plugin) was not up-to-date relatively to the [plugin example](https://github.com/cyberbotics/webots_ros2/blob/master/webots_ros2_turtlebot/webots_ros2_turtlebot/plugin_example.py) with the `Turtlebot` demo.
This PR simply updates the plugin in `Turtlebot` as the tutorial has been also updated.
Entry points for plugins are also removed as they are not necessary.
> Update Python plugin example with GitHub tutorial

- webots_ros2_control/src/Ros2ControlSystem.cpp
I believe I introduce the bug in #415
> Fix motor without sensor

- webots_ros2_control/CMakeLists.txt
- webots_ros2_control/include/webots_ros2_control/Ros2ControlSystem.hpp
- webots_ros2_control/src/Ros2Control.cpp
- webots_ros2_control/src/Ros2ControlSystem.cpp
- webots_ros2_driver/CMakeLists.txt
Fixes: https://github.com/cyberbotics/webots_ros2/issues/451
> Fix build from repo

- webots_ros2_epuck/worlds/epuck_world.wbt
- webots_ros2_epuck/worlds/rats_life_benchmark.wbt
- webots_ros2_mavic/worlds/mavic_world.wbt
- webots_ros2_tesla/worlds/tesla_world.wbt
- webots_ros2_tests/worlds/driver_test.wbt
- webots_ros2_tiago/worlds/default.wbt
- webots_ros2_turtlebot/worlds/turtlebot3_burger_example.wbt
- webots_ros2_universal_robot/worlds/robotic_arms.wbt
- webots_ros2_universal_robot/worlds/universal_robot.wbt
> Add EXTERNPROTO declaration to worlds

- webots_ros2_driver/package.xml
- webots_ros2_driver/webots_ros2_driver/ros2_supervisor.py
> Remove external urdf2webots dependency

- webots_ros2/package.xml
- webots_ros2/setup.py
- webots_ros2_control/package.xml
- webots_ros2_core/package.xml
- webots_ros2_core/setup.py
- webots_ros2_driver/package.xml
- webots_ros2_epuck/package.xml
- webots_ros2_epuck/setup.py
- webots_ros2_importer/CHANGELOG.rst
- webots_ros2_importer/package.xml
- webots_ros2_importer/setup.py
- webots_ros2_mavic/package.xml
- webots_ros2_mavic/setup.py
- webots_ros2_msgs/package.xml
- webots_ros2_tesla/package.xml
- webots_ros2_tesla/setup.py
- webots_ros2_tests/package.xml
- webots_ros2_tests/setup.py
- webots_ros2_tiago/package.xml
- webots_ros2_tiago/setup.py
- webots_ros2_turtlebot/package.xml
- webots_ros2_turtlebot/setup.py
- webots_ros2_universal_robot/package.xml
- webots_ros2_universal_robot/setup.py
> Update version 2022.1.1

- webots_ros2/package.xml
- webots_ros2/setup.py
- webots_ros2_control/package.xml
- webots_ros2_core/package.xml
- webots_ros2_core/setup.py
- webots_ros2_driver/CHANGELOG.rst
- webots_ros2_driver/package.xml
- webots_ros2_epuck/CHANGELOG.rst
- webots_ros2_epuck/package.xml
- webots_ros2_epuck/setup.py
- webots_ros2_importer/package.xml
- webots_ros2_importer/setup.py
- webots_ros2_mavic/CHANGELOG.rst
- webots_ros2_mavic/package.xml
- webots_ros2_mavic/setup.py
- webots_ros2_msgs/package.xml
- webots_ros2_tesla/CHANGELOG.rst
- webots_ros2_tesla/package.xml
- webots_ros2_tesla/setup.py
- webots_ros2_tests/package.xml
- webots_ros2_tests/setup.py
- webots_ros2_tiago/CHANGELOG.rst
- webots_ros2_tiago/package.xml
- webots_ros2_tiago/setup.py
- webots_ros2_turtlebot/CHANGELOG.rst
- webots_ros2_turtlebot/package.xml
- webots_ros2_turtlebot/setup.py
- webots_ros2_universal_robot/CHANGELOG.rst
- webots_ros2_universal_robot/package.xml
- webots_ros2_universal_robot/setup.py
> Prepare version 2022.1.2

- webots_ros2_driver/webots_ros2_driver/webots_launcher.py
Due to an incorrect merge, the fix was reverted
> Restore relative url fix

- webots_ros2/CHANGELOG.rst
- webots_ros2_driver/CHANGELOG.rst
- webots_ros2_driver/src/plugins/static/Ros2Camera.cpp
- webots_ros2_importer/CHANGELOG.rst
- webots_ros2_importer/webots_ros2_importer/urdf2proto.py
Fixes https://github.com/cyberbotics/webots_ros2/issues/515
> Upgrade urdf2webots to 2.0.3

- webots_ros2/CHANGELOG.rst
- webots_ros2/package.xml
- webots_ros2/setup.py
- webots_ros2_control/package.xml
- webots_ros2_core/package.xml
- webots_ros2_core/setup.py
- webots_ros2_driver/CHANGELOG.rst
- webots_ros2_driver/package.xml
- webots_ros2_epuck/package.xml
- webots_ros2_epuck/setup.py
- webots_ros2_importer/CHANGELOG.rst
- webots_ros2_importer/package.xml
- webots_ros2_importer/setup.py
- webots_ros2_mavic/package.xml
- webots_ros2_mavic/setup.py
- webots_ros2_msgs/package.xml
- webots_ros2_tesla/package.xml
- webots_ros2_tesla/setup.py
- webots_ros2_tests/CHANGELOG.rst
- webots_ros2_tests/package.xml
- webots_ros2_tests/setup.py
- webots_ros2_tiago/package.xml
- webots_ros2_tiago/setup.py
- webots_ros2_turtlebot/package.xml
- webots_ros2_turtlebot/setup.py
- webots_ros2_universal_robot/package.xml
- webots_ros2_universal_robot/setup.py
> Prepare for version 2022.1.4 update

- scripts/ci_before_init_embed.bash
> Upgrade to R2023a (master)

- webots_ros2_driver/webots/projects/default/libraries/vehicle/java/.gitignore
> Add missing gitignore in java libvehicle

- scripts/sync_controller_lib.sh
> Fix missing gitignore sync

- webots_ros2_control/CMakeLists.txt
- webots_ros2_control/src/Ros2Control.cpp
> Improve comparison

- webots_ros2/CHANGELOG.rst
- webots_ros2/package.xml
- webots_ros2/setup.py
- webots_ros2_control/package.xml
- webots_ros2_driver/CHANGELOG.rst
- webots_ros2_driver/package.xml
- webots_ros2_epuck/CHANGELOG.rst
- webots_ros2_epuck/package.xml
- webots_ros2_epuck/setup.py
- webots_ros2_importer/package.xml
- webots_ros2_importer/setup.py
- webots_ros2_mavic/package.xml
- webots_ros2_mavic/setup.py
- webots_ros2_msgs/package.xml
- webots_ros2_tesla/package.xml
- webots_ros2_tesla/setup.py
- webots_ros2_tests/package.xml
- webots_ros2_tests/setup.py
- webots_ros2_tiago/package.xml
- webots_ros2_tiago/setup.py
- webots_ros2_turtlebot/package.xml
- webots_ros2_turtlebot/setup.py
- webots_ros2_universal_robot/package.xml
- webots_ros2_universal_robot/setup.py
> Prepare 2023.0.1

- webots_ros2/CHANGELOG.rst
- webots_ros2/package.xml
- webots_ros2/setup.py
- webots_ros2_control/package.xml
- webots_ros2_driver/CHANGELOG.rst
- webots_ros2_driver/package.xml
- webots_ros2_epuck/CHANGELOG.rst
- webots_ros2_epuck/package.xml
- webots_ros2_epuck/setup.py
- webots_ros2_importer/package.xml
- webots_ros2_importer/setup.py
- webots_ros2_mavic/CHANGELOG.rst
- webots_ros2_mavic/package.xml
- webots_ros2_mavic/setup.py
- webots_ros2_msgs/package.xml
- webots_ros2_tesla/CHANGELOG.rst
- webots_ros2_tesla/package.xml
- webots_ros2_tesla/setup.py
- webots_ros2_tests/package.xml
- webots_ros2_tests/setup.py
- webots_ros2_tiago/CHANGELOG.rst
- webots_ros2_tiago/package.xml
- webots_ros2_tiago/setup.py
- webots_ros2_turtlebot/CHANGELOG.rst
- webots_ros2_turtlebot/package.xml
- webots_ros2_turtlebot/setup.py
- webots_ros2_universal_robot/CHANGELOG.rst
- webots_ros2_universal_robot/package.xml
- webots_ros2_universal_robot/setup.py
> Prepare 2023.0.2

- scripts/sync_controller_lib.sh
> Copy version.txt to libcontroller in master

- webots_ros2_mavic/webots_ros2_mavic/mavic_driver.py
> Rename gyro variables to velocity

- webots_ros2/CHANGELOG.rst
- webots_ros2_driver/CHANGELOG.rst
> Add missing features in changelog

- webots_ros2_driver/include/webots_ros2_driver/plugins/static/Ros2Emitter.hpp
- webots_ros2_driver/include/webots_ros2_driver/plugins/static/Ros2Receiver.hpp
- webots_ros2_driver/src/plugins/static/Ros2Emitter.cpp
- webots_ros2_driver/src/plugins/static/Ros2Receiver.cpp
- webots_ros2_msgs/CMakeLists.txt
- webots_ros2_msgs/srv/EmitterSendString.srv
- webots_ros2_msgs/srv/GetFloat.srv
- webots_ros2_msgs/srv/GetInt.srv
- webots_ros2_msgs/srv/ReceiverGetEmitterDirection.srv
- webots_ros2_msgs/srv/SetFloat.srv
- webots_ros2_msgs/srv/SetInt.srv
As continuation PR #680 on adding standard behavior such as #677
> Fix Emitter and Receiver devices

- webots_ros2/CHANGELOG.rst
- webots_ros2_driver/CHANGELOG.rst
- webots_ros2_driver/CMakeLists.txt
- webots_ros2_driver/include/webots_ros2_driver/plugins/dynamic/Ros2RGBD.hpp
- webots_ros2_driver/src/plugins/dynamic/Ros2RGBD.cpp
- webots_ros2_driver/webots_ros2_rgbd.xml
- webots_ros2_tests/CHANGELOG.rst
- webots_ros2_tests/resource/driver_test.urdf
- webots_ros2_tests/test/test_system_driver.py
Implements a plugin that merges RGB images from a Camera node and depth images from a RangeFinder node to create a painted point cloud.
- webots_ros2_tests
> Add RGB point cloud

- .github/workflows/test_develop.yml
> Fix nightly tests on develop branch

- webots_ros2_universal_robot/webots_ros2_universal_robot/follow_joint_trajectory_client.py
Backport changes of #726 to develop.
> Backport CI fix to develop

- webots_ros2_tiago/worlds/.default.wbproj
- webots_ros2_tiago/worlds/default.wbt
> Clear unused devices in TIAGo example

- webots_ros2_tiago/worlds/.default.wbproj
- webots_ros2_tiago/worlds/default.wbt
> Backport TIAGo cleanup to develop

- webots_ros2/CHANGELOG.rst
- webots_ros2/package.xml
- webots_ros2/setup.py
- webots_ros2_control/package.xml
- webots_ros2_driver/CHANGELOG.rst
- webots_ros2_driver/package.xml
- webots_ros2_epuck/CHANGELOG.rst
- webots_ros2_epuck/package.xml
- webots_ros2_epuck/setup.py
- webots_ros2_importer/CHANGELOG.rst
- webots_ros2_importer/package.xml
- webots_ros2_importer/setup.py
- webots_ros2_mavic/package.xml
- webots_ros2_mavic/setup.py
- webots_ros2_msgs/package.xml
- webots_ros2_tesla/package.xml
- webots_ros2_tesla/setup.py
- webots_ros2_tests/CHANGELOG.rst
- webots_ros2_tests/package.xml
- webots_ros2_tests/setup.py
- webots_ros2_tiago/CHANGELOG.rst
- webots_ros2_tiago/package.xml
- webots_ros2_tiago/setup.py
- webots_ros2_turtlebot/CHANGELOG.rst
- webots_ros2_turtlebot/package.xml
- webots_ros2_turtlebot/setup.py
- webots_ros2_universal_robot/CHANGELOG.rst
- webots_ros2_universal_robot/package.xml
- webots_ros2_universal_robot/setup.py
> Prepare 2023.0.4

- webots_ros2/CHANGELOG.rst
- webots_ros2_driver/CHANGELOG.rst
- webots_ros2_driver/src/plugins/static/Ros2Camera.cpp
- webots_ros2_driver/src/plugins/static/Ros2RangeFinder.cpp
- webots_ros2_tesla/webots_ros2_tesla/lane_follower.py
- webots_ros2_tests/test/test_system_driver.py
- webots_ros2_tests/test/test_system_epuck.py
- webots_ros2_tests/test/test_system_tesla.py
> 749 ros2camera publishes non canonical topics and camera info

- scripts/ci_before_init_embed.bash
- webots_ros2_driver/webots_ros2_driver/utils.py
> Update default Webots version in CI and WebotsLauncher

- webots_ros2/CHANGELOG.rst
- webots_ros2/package.xml
- webots_ros2/setup.py
- webots_ros2_control/package.xml
- webots_ros2_driver/CHANGELOG.rst
- webots_ros2_driver/package.xml
- webots_ros2_epuck/package.xml
- webots_ros2_epuck/setup.py
- webots_ros2_importer/package.xml
- webots_ros2_importer/setup.py
- webots_ros2_mavic/package.xml
- webots_ros2_mavic/setup.py
- webots_ros2_msgs/package.xml
- webots_ros2_tesla/package.xml
- webots_ros2_tesla/setup.py
- webots_ros2_tests/package.xml
- webots_ros2_tests/setup.py
- webots_ros2_tiago/package.xml
- webots_ros2_tiago/setup.py
- webots_ros2_turtlebot/package.xml
- webots_ros2_turtlebot/setup.py
- webots_ros2_universal_robot/package.xml
- webots_ros2_universal_robot/setup.py
- Version upgrade
- Changelogs release date
When this PR is merged, the last change to wait for before submitting the release is the synchronization with the libController about the Webots version (see https://github.com/cyberbotics/webots/pull/6315).
> Prepare for version 2023.1.1

- scripts/ci_after_init.bash
Fixes https://github.com/cyberbotics/webots_ros2/issues/830
> Fix missing YAML cpp library

- scripts/ci_after_init.bash
- webots_ros2_driver/package.xml
Fixes #833 
Add libyaml-cpp dependency to package.
> Fix buildfarm dependency

- webots_ros2/CHANGELOG.rst
- webots_ros2/package.xml
- webots_ros2/setup.py
- webots_ros2_control/CHANGELOG.rst
- webots_ros2_control/package.xml
- webots_ros2_driver/CHANGELOG.rst
- webots_ros2_driver/package.xml
- webots_ros2_epuck/package.xml
- webots_ros2_epuck/setup.py
- webots_ros2_importer/package.xml
- webots_ros2_importer/setup.py
- webots_ros2_mavic/package.xml
- webots_ros2_mavic/setup.py
- webots_ros2_msgs/package.xml
- webots_ros2_tesla/package.xml
- webots_ros2_tesla/setup.py
- webots_ros2_tests/package.xml
- webots_ros2_tests/setup.py
- webots_ros2_tiago/package.xml
- webots_ros2_tiago/setup.py
- webots_ros2_turtlebot/package.xml
- webots_ros2_turtlebot/setup.py
- webots_ros2_universal_robot/CHANGELOG.rst
- webots_ros2_universal_robot/package.xml
- webots_ros2_universal_robot/setup.py
This PR performs version upgrade to 2023.1.3.
Once merged the release procedure can be followed from [section Tag](https://github.com/cyberbotics/webots_ros2/wiki/Internal-Publishing#tag).
> Prepare for version 2023.1.3

- .github/workflows/libcontroller_updater.yml
- .github/workflows/sync_master_to_develop.yml
> Disable automatic controller syncs
